# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/magnus/Projects/cpp/nekohook

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/magnus/Projects/cpp/nekohook

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/magnus/Projects/cpp/nekohook && $(CMAKE_COMMAND) -E cmake_progress_start /home/magnus/Projects/cpp/nekohook/CMakeFiles /home/magnus/Projects/cpp/nekohook/src/modules/gl_draw/libglez/CMakeFiles/progress.marks
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f CMakeFiles/Makefile2 src/modules/gl_draw/libglez/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/magnus/Projects/cpp/nekohook/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f CMakeFiles/Makefile2 src/modules/gl_draw/libglez/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f CMakeFiles/Makefile2 src/modules/gl_draw/libglez/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f CMakeFiles/Makefile2 src/modules/gl_draw/libglez/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/magnus/Projects/cpp/nekohook && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/modules/gl_draw/libglez/CMakeFiles/glez.dir/rule:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f CMakeFiles/Makefile2 src/modules/gl_draw/libglez/CMakeFiles/glez.dir/rule
.PHONY : src/modules/gl_draw/libglez/CMakeFiles/glez.dir/rule

# Convenience name for target.
glez: src/modules/gl_draw/libglez/CMakeFiles/glez.dir/rule

.PHONY : glez

# fast build rule for target.
glez/fast:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build
.PHONY : glez/fast

ftgl/distance-field.o: ftgl/distance-field.c.o

.PHONY : ftgl/distance-field.o

# target to build an object file
ftgl/distance-field.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/distance-field.c.o
.PHONY : ftgl/distance-field.c.o

ftgl/distance-field.i: ftgl/distance-field.c.i

.PHONY : ftgl/distance-field.i

# target to preprocess a source file
ftgl/distance-field.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/distance-field.c.i
.PHONY : ftgl/distance-field.c.i

ftgl/distance-field.s: ftgl/distance-field.c.s

.PHONY : ftgl/distance-field.s

# target to generate assembly for a file
ftgl/distance-field.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/distance-field.c.s
.PHONY : ftgl/distance-field.c.s

ftgl/edtaa3func.o: ftgl/edtaa3func.c.o

.PHONY : ftgl/edtaa3func.o

# target to build an object file
ftgl/edtaa3func.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/edtaa3func.c.o
.PHONY : ftgl/edtaa3func.c.o

ftgl/edtaa3func.i: ftgl/edtaa3func.c.i

.PHONY : ftgl/edtaa3func.i

# target to preprocess a source file
ftgl/edtaa3func.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/edtaa3func.c.i
.PHONY : ftgl/edtaa3func.c.i

ftgl/edtaa3func.s: ftgl/edtaa3func.c.s

.PHONY : ftgl/edtaa3func.s

# target to generate assembly for a file
ftgl/edtaa3func.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/edtaa3func.c.s
.PHONY : ftgl/edtaa3func.c.s

ftgl/font-manager.o: ftgl/font-manager.c.o

.PHONY : ftgl/font-manager.o

# target to build an object file
ftgl/font-manager.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/font-manager.c.o
.PHONY : ftgl/font-manager.c.o

ftgl/font-manager.i: ftgl/font-manager.c.i

.PHONY : ftgl/font-manager.i

# target to preprocess a source file
ftgl/font-manager.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/font-manager.c.i
.PHONY : ftgl/font-manager.c.i

ftgl/font-manager.s: ftgl/font-manager.c.s

.PHONY : ftgl/font-manager.s

# target to generate assembly for a file
ftgl/font-manager.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/font-manager.c.s
.PHONY : ftgl/font-manager.c.s

ftgl/makefont.o: ftgl/makefont.c.o

.PHONY : ftgl/makefont.o

# target to build an object file
ftgl/makefont.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/makefont.c.o
.PHONY : ftgl/makefont.c.o

ftgl/makefont.i: ftgl/makefont.c.i

.PHONY : ftgl/makefont.i

# target to preprocess a source file
ftgl/makefont.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/makefont.c.i
.PHONY : ftgl/makefont.c.i

ftgl/makefont.s: ftgl/makefont.c.s

.PHONY : ftgl/makefont.s

# target to generate assembly for a file
ftgl/makefont.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/makefont.c.s
.PHONY : ftgl/makefont.c.s

ftgl/mat4.o: ftgl/mat4.c.o

.PHONY : ftgl/mat4.o

# target to build an object file
ftgl/mat4.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/mat4.c.o
.PHONY : ftgl/mat4.c.o

ftgl/mat4.i: ftgl/mat4.c.i

.PHONY : ftgl/mat4.i

# target to preprocess a source file
ftgl/mat4.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/mat4.c.i
.PHONY : ftgl/mat4.c.i

ftgl/mat4.s: ftgl/mat4.c.s

.PHONY : ftgl/mat4.s

# target to generate assembly for a file
ftgl/mat4.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/mat4.c.s
.PHONY : ftgl/mat4.c.s

ftgl/platform.o: ftgl/platform.c.o

.PHONY : ftgl/platform.o

# target to build an object file
ftgl/platform.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/platform.c.o
.PHONY : ftgl/platform.c.o

ftgl/platform.i: ftgl/platform.c.i

.PHONY : ftgl/platform.i

# target to preprocess a source file
ftgl/platform.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/platform.c.i
.PHONY : ftgl/platform.c.i

ftgl/platform.s: ftgl/platform.c.s

.PHONY : ftgl/platform.s

# target to generate assembly for a file
ftgl/platform.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/platform.c.s
.PHONY : ftgl/platform.c.s

ftgl/text-buffer.o: ftgl/text-buffer.c.o

.PHONY : ftgl/text-buffer.o

# target to build an object file
ftgl/text-buffer.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/text-buffer.c.o
.PHONY : ftgl/text-buffer.c.o

ftgl/text-buffer.i: ftgl/text-buffer.c.i

.PHONY : ftgl/text-buffer.i

# target to preprocess a source file
ftgl/text-buffer.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/text-buffer.c.i
.PHONY : ftgl/text-buffer.c.i

ftgl/text-buffer.s: ftgl/text-buffer.c.s

.PHONY : ftgl/text-buffer.s

# target to generate assembly for a file
ftgl/text-buffer.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/text-buffer.c.s
.PHONY : ftgl/text-buffer.c.s

ftgl/texture-atlas.o: ftgl/texture-atlas.c.o

.PHONY : ftgl/texture-atlas.o

# target to build an object file
ftgl/texture-atlas.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/texture-atlas.c.o
.PHONY : ftgl/texture-atlas.c.o

ftgl/texture-atlas.i: ftgl/texture-atlas.c.i

.PHONY : ftgl/texture-atlas.i

# target to preprocess a source file
ftgl/texture-atlas.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/texture-atlas.c.i
.PHONY : ftgl/texture-atlas.c.i

ftgl/texture-atlas.s: ftgl/texture-atlas.c.s

.PHONY : ftgl/texture-atlas.s

# target to generate assembly for a file
ftgl/texture-atlas.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/texture-atlas.c.s
.PHONY : ftgl/texture-atlas.c.s

ftgl/texture-font.o: ftgl/texture-font.c.o

.PHONY : ftgl/texture-font.o

# target to build an object file
ftgl/texture-font.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/texture-font.c.o
.PHONY : ftgl/texture-font.c.o

ftgl/texture-font.i: ftgl/texture-font.c.i

.PHONY : ftgl/texture-font.i

# target to preprocess a source file
ftgl/texture-font.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/texture-font.c.i
.PHONY : ftgl/texture-font.c.i

ftgl/texture-font.s: ftgl/texture-font.c.s

.PHONY : ftgl/texture-font.s

# target to generate assembly for a file
ftgl/texture-font.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/texture-font.c.s
.PHONY : ftgl/texture-font.c.s

ftgl/utf8-utils.o: ftgl/utf8-utils.c.o

.PHONY : ftgl/utf8-utils.o

# target to build an object file
ftgl/utf8-utils.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/utf8-utils.c.o
.PHONY : ftgl/utf8-utils.c.o

ftgl/utf8-utils.i: ftgl/utf8-utils.c.i

.PHONY : ftgl/utf8-utils.i

# target to preprocess a source file
ftgl/utf8-utils.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/utf8-utils.c.i
.PHONY : ftgl/utf8-utils.c.i

ftgl/utf8-utils.s: ftgl/utf8-utils.c.s

.PHONY : ftgl/utf8-utils.s

# target to generate assembly for a file
ftgl/utf8-utils.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/utf8-utils.c.s
.PHONY : ftgl/utf8-utils.c.s

ftgl/vector.o: ftgl/vector.c.o

.PHONY : ftgl/vector.o

# target to build an object file
ftgl/vector.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/vector.c.o
.PHONY : ftgl/vector.c.o

ftgl/vector.i: ftgl/vector.c.i

.PHONY : ftgl/vector.i

# target to preprocess a source file
ftgl/vector.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/vector.c.i
.PHONY : ftgl/vector.c.i

ftgl/vector.s: ftgl/vector.c.s

.PHONY : ftgl/vector.s

# target to generate assembly for a file
ftgl/vector.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/vector.c.s
.PHONY : ftgl/vector.c.s

ftgl/vertex-attribute.o: ftgl/vertex-attribute.c.o

.PHONY : ftgl/vertex-attribute.o

# target to build an object file
ftgl/vertex-attribute.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/vertex-attribute.c.o
.PHONY : ftgl/vertex-attribute.c.o

ftgl/vertex-attribute.i: ftgl/vertex-attribute.c.i

.PHONY : ftgl/vertex-attribute.i

# target to preprocess a source file
ftgl/vertex-attribute.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/vertex-attribute.c.i
.PHONY : ftgl/vertex-attribute.c.i

ftgl/vertex-attribute.s: ftgl/vertex-attribute.c.s

.PHONY : ftgl/vertex-attribute.s

# target to generate assembly for a file
ftgl/vertex-attribute.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/vertex-attribute.c.s
.PHONY : ftgl/vertex-attribute.c.s

ftgl/vertex-buffer.o: ftgl/vertex-buffer.c.o

.PHONY : ftgl/vertex-buffer.o

# target to build an object file
ftgl/vertex-buffer.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/vertex-buffer.c.o
.PHONY : ftgl/vertex-buffer.c.o

ftgl/vertex-buffer.i: ftgl/vertex-buffer.c.i

.PHONY : ftgl/vertex-buffer.i

# target to preprocess a source file
ftgl/vertex-buffer.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/vertex-buffer.c.i
.PHONY : ftgl/vertex-buffer.c.i

ftgl/vertex-buffer.s: ftgl/vertex-buffer.c.s

.PHONY : ftgl/vertex-buffer.s

# target to generate assembly for a file
ftgl/vertex-buffer.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/ftgl/vertex-buffer.c.s
.PHONY : ftgl/vertex-buffer.c.s

src/draw.o: src/draw.c.o

.PHONY : src/draw.o

# target to build an object file
src/draw.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/draw.c.o
.PHONY : src/draw.c.o

src/draw.i: src/draw.c.i

.PHONY : src/draw.i

# target to preprocess a source file
src/draw.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/draw.c.i
.PHONY : src/draw.c.i

src/draw.s: src/draw.c.s

.PHONY : src/draw.s

# target to generate assembly for a file
src/draw.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/draw.c.s
.PHONY : src/draw.c.s

src/fonts.o: src/fonts.c.o

.PHONY : src/fonts.o

# target to build an object file
src/fonts.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/fonts.c.o
.PHONY : src/fonts.c.o

src/fonts.i: src/fonts.c.i

.PHONY : src/fonts.i

# target to preprocess a source file
src/fonts.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/fonts.c.i
.PHONY : src/fonts.c.i

src/fonts.s: src/fonts.c.s

.PHONY : src/fonts.s

# target to generate assembly for a file
src/fonts.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/fonts.c.s
.PHONY : src/fonts.c.s

src/glez.o: src/glez.c.o

.PHONY : src/glez.o

# target to build an object file
src/glez.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/glez.c.o
.PHONY : src/glez.c.o

src/glez.i: src/glez.c.i

.PHONY : src/glez.i

# target to preprocess a source file
src/glez.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/glez.c.i
.PHONY : src/glez.c.i

src/glez.s: src/glez.c.s

.PHONY : src/glez.s

# target to generate assembly for a file
src/glez.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/glez.c.s
.PHONY : src/glez.c.s

src/program.o: src/program.c.o

.PHONY : src/program.o

# target to build an object file
src/program.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/program.c.o
.PHONY : src/program.c.o

src/program.i: src/program.c.i

.PHONY : src/program.i

# target to preprocess a source file
src/program.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/program.c.i
.PHONY : src/program.c.i

src/program.s: src/program.c.s

.PHONY : src/program.s

# target to generate assembly for a file
src/program.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/program.c.s
.PHONY : src/program.c.s

src/textures.o: src/textures.c.o

.PHONY : src/textures.o

# target to build an object file
src/textures.c.o:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/textures.c.o
.PHONY : src/textures.c.o

src/textures.i: src/textures.c.i

.PHONY : src/textures.i

# target to preprocess a source file
src/textures.c.i:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/textures.c.i
.PHONY : src/textures.c.i

src/textures.s: src/textures.c.s

.PHONY : src/textures.s

# target to generate assembly for a file
src/textures.c.s:
	cd /home/magnus/Projects/cpp/nekohook && $(MAKE) -f src/modules/gl_draw/libglez/CMakeFiles/glez.dir/build.make src/modules/gl_draw/libglez/CMakeFiles/glez.dir/src/textures.c.s
.PHONY : src/textures.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... glez"
	@echo "... edit_cache"
	@echo "... ftgl/distance-field.o"
	@echo "... ftgl/distance-field.i"
	@echo "... ftgl/distance-field.s"
	@echo "... ftgl/edtaa3func.o"
	@echo "... ftgl/edtaa3func.i"
	@echo "... ftgl/edtaa3func.s"
	@echo "... ftgl/font-manager.o"
	@echo "... ftgl/font-manager.i"
	@echo "... ftgl/font-manager.s"
	@echo "... ftgl/makefont.o"
	@echo "... ftgl/makefont.i"
	@echo "... ftgl/makefont.s"
	@echo "... ftgl/mat4.o"
	@echo "... ftgl/mat4.i"
	@echo "... ftgl/mat4.s"
	@echo "... ftgl/platform.o"
	@echo "... ftgl/platform.i"
	@echo "... ftgl/platform.s"
	@echo "... ftgl/text-buffer.o"
	@echo "... ftgl/text-buffer.i"
	@echo "... ftgl/text-buffer.s"
	@echo "... ftgl/texture-atlas.o"
	@echo "... ftgl/texture-atlas.i"
	@echo "... ftgl/texture-atlas.s"
	@echo "... ftgl/texture-font.o"
	@echo "... ftgl/texture-font.i"
	@echo "... ftgl/texture-font.s"
	@echo "... ftgl/utf8-utils.o"
	@echo "... ftgl/utf8-utils.i"
	@echo "... ftgl/utf8-utils.s"
	@echo "... ftgl/vector.o"
	@echo "... ftgl/vector.i"
	@echo "... ftgl/vector.s"
	@echo "... ftgl/vertex-attribute.o"
	@echo "... ftgl/vertex-attribute.i"
	@echo "... ftgl/vertex-attribute.s"
	@echo "... ftgl/vertex-buffer.o"
	@echo "... ftgl/vertex-buffer.i"
	@echo "... ftgl/vertex-buffer.s"
	@echo "... src/draw.o"
	@echo "... src/draw.i"
	@echo "... src/draw.s"
	@echo "... src/fonts.o"
	@echo "... src/fonts.i"
	@echo "... src/fonts.s"
	@echo "... src/glez.o"
	@echo "... src/glez.i"
	@echo "... src/glez.s"
	@echo "... src/program.o"
	@echo "... src/program.i"
	@echo "... src/program.s"
	@echo "... src/textures.o"
	@echo "... src/textures.i"
	@echo "... src/textures.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/magnus/Projects/cpp/nekohook && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

