# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/nullifiedcat/9b56ed3a-b8e2-4ab9-bccf-21774e3af4df/MIGRATE/HOME/workspace/catbase/libglez

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/nullifiedcat/9b56ed3a-b8e2-4ab9-bccf-21774e3af4df/MIGRATE/HOME/workspace/catbase/libglez

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/nullifiedcat/9b56ed3a-b8e2-4ab9-bccf-21774e3af4df/MIGRATE/HOME/workspace/catbase/libglez/CMakeFiles /media/nullifiedcat/9b56ed3a-b8e2-4ab9-bccf-21774e3af4df/MIGRATE/HOME/workspace/catbase/libglez/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/nullifiedcat/9b56ed3a-b8e2-4ab9-bccf-21774e3af4df/MIGRATE/HOME/workspace/catbase/libglez/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glez32

# Build rule for target.
glez32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glez32
.PHONY : glez32

# fast build rule for target.
glez32/fast:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/build
.PHONY : glez32/fast

#=============================================================================
# Target rules for targets named glez64

# Build rule for target.
glez64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glez64
.PHONY : glez64

# fast build rule for target.
glez64/fast:
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/build
.PHONY : glez64/fast

ftgl/distance-field.o: ftgl/distance-field.c.o

.PHONY : ftgl/distance-field.o

# target to build an object file
ftgl/distance-field.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/distance-field.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/distance-field.c.o
.PHONY : ftgl/distance-field.c.o

ftgl/distance-field.i: ftgl/distance-field.c.i

.PHONY : ftgl/distance-field.i

# target to preprocess a source file
ftgl/distance-field.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/distance-field.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/distance-field.c.i
.PHONY : ftgl/distance-field.c.i

ftgl/distance-field.s: ftgl/distance-field.c.s

.PHONY : ftgl/distance-field.s

# target to generate assembly for a file
ftgl/distance-field.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/distance-field.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/distance-field.c.s
.PHONY : ftgl/distance-field.c.s

ftgl/edtaa3func.o: ftgl/edtaa3func.c.o

.PHONY : ftgl/edtaa3func.o

# target to build an object file
ftgl/edtaa3func.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/edtaa3func.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/edtaa3func.c.o
.PHONY : ftgl/edtaa3func.c.o

ftgl/edtaa3func.i: ftgl/edtaa3func.c.i

.PHONY : ftgl/edtaa3func.i

# target to preprocess a source file
ftgl/edtaa3func.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/edtaa3func.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/edtaa3func.c.i
.PHONY : ftgl/edtaa3func.c.i

ftgl/edtaa3func.s: ftgl/edtaa3func.c.s

.PHONY : ftgl/edtaa3func.s

# target to generate assembly for a file
ftgl/edtaa3func.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/edtaa3func.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/edtaa3func.c.s
.PHONY : ftgl/edtaa3func.c.s

ftgl/font-manager.o: ftgl/font-manager.c.o

.PHONY : ftgl/font-manager.o

# target to build an object file
ftgl/font-manager.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/font-manager.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/font-manager.c.o
.PHONY : ftgl/font-manager.c.o

ftgl/font-manager.i: ftgl/font-manager.c.i

.PHONY : ftgl/font-manager.i

# target to preprocess a source file
ftgl/font-manager.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/font-manager.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/font-manager.c.i
.PHONY : ftgl/font-manager.c.i

ftgl/font-manager.s: ftgl/font-manager.c.s

.PHONY : ftgl/font-manager.s

# target to generate assembly for a file
ftgl/font-manager.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/font-manager.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/font-manager.c.s
.PHONY : ftgl/font-manager.c.s

ftgl/makefont.o: ftgl/makefont.c.o

.PHONY : ftgl/makefont.o

# target to build an object file
ftgl/makefont.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/makefont.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/makefont.c.o
.PHONY : ftgl/makefont.c.o

ftgl/makefont.i: ftgl/makefont.c.i

.PHONY : ftgl/makefont.i

# target to preprocess a source file
ftgl/makefont.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/makefont.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/makefont.c.i
.PHONY : ftgl/makefont.c.i

ftgl/makefont.s: ftgl/makefont.c.s

.PHONY : ftgl/makefont.s

# target to generate assembly for a file
ftgl/makefont.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/makefont.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/makefont.c.s
.PHONY : ftgl/makefont.c.s

ftgl/mat4.o: ftgl/mat4.c.o

.PHONY : ftgl/mat4.o

# target to build an object file
ftgl/mat4.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/mat4.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/mat4.c.o
.PHONY : ftgl/mat4.c.o

ftgl/mat4.i: ftgl/mat4.c.i

.PHONY : ftgl/mat4.i

# target to preprocess a source file
ftgl/mat4.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/mat4.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/mat4.c.i
.PHONY : ftgl/mat4.c.i

ftgl/mat4.s: ftgl/mat4.c.s

.PHONY : ftgl/mat4.s

# target to generate assembly for a file
ftgl/mat4.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/mat4.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/mat4.c.s
.PHONY : ftgl/mat4.c.s

ftgl/platform.o: ftgl/platform.c.o

.PHONY : ftgl/platform.o

# target to build an object file
ftgl/platform.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/platform.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/platform.c.o
.PHONY : ftgl/platform.c.o

ftgl/platform.i: ftgl/platform.c.i

.PHONY : ftgl/platform.i

# target to preprocess a source file
ftgl/platform.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/platform.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/platform.c.i
.PHONY : ftgl/platform.c.i

ftgl/platform.s: ftgl/platform.c.s

.PHONY : ftgl/platform.s

# target to generate assembly for a file
ftgl/platform.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/platform.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/platform.c.s
.PHONY : ftgl/platform.c.s

ftgl/text-buffer.o: ftgl/text-buffer.c.o

.PHONY : ftgl/text-buffer.o

# target to build an object file
ftgl/text-buffer.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/text-buffer.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/text-buffer.c.o
.PHONY : ftgl/text-buffer.c.o

ftgl/text-buffer.i: ftgl/text-buffer.c.i

.PHONY : ftgl/text-buffer.i

# target to preprocess a source file
ftgl/text-buffer.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/text-buffer.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/text-buffer.c.i
.PHONY : ftgl/text-buffer.c.i

ftgl/text-buffer.s: ftgl/text-buffer.c.s

.PHONY : ftgl/text-buffer.s

# target to generate assembly for a file
ftgl/text-buffer.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/text-buffer.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/text-buffer.c.s
.PHONY : ftgl/text-buffer.c.s

ftgl/texture-atlas.o: ftgl/texture-atlas.c.o

.PHONY : ftgl/texture-atlas.o

# target to build an object file
ftgl/texture-atlas.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/texture-atlas.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/texture-atlas.c.o
.PHONY : ftgl/texture-atlas.c.o

ftgl/texture-atlas.i: ftgl/texture-atlas.c.i

.PHONY : ftgl/texture-atlas.i

# target to preprocess a source file
ftgl/texture-atlas.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/texture-atlas.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/texture-atlas.c.i
.PHONY : ftgl/texture-atlas.c.i

ftgl/texture-atlas.s: ftgl/texture-atlas.c.s

.PHONY : ftgl/texture-atlas.s

# target to generate assembly for a file
ftgl/texture-atlas.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/texture-atlas.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/texture-atlas.c.s
.PHONY : ftgl/texture-atlas.c.s

ftgl/texture-font.o: ftgl/texture-font.c.o

.PHONY : ftgl/texture-font.o

# target to build an object file
ftgl/texture-font.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/texture-font.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/texture-font.c.o
.PHONY : ftgl/texture-font.c.o

ftgl/texture-font.i: ftgl/texture-font.c.i

.PHONY : ftgl/texture-font.i

# target to preprocess a source file
ftgl/texture-font.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/texture-font.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/texture-font.c.i
.PHONY : ftgl/texture-font.c.i

ftgl/texture-font.s: ftgl/texture-font.c.s

.PHONY : ftgl/texture-font.s

# target to generate assembly for a file
ftgl/texture-font.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/texture-font.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/texture-font.c.s
.PHONY : ftgl/texture-font.c.s

ftgl/utf8-utils.o: ftgl/utf8-utils.c.o

.PHONY : ftgl/utf8-utils.o

# target to build an object file
ftgl/utf8-utils.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/utf8-utils.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/utf8-utils.c.o
.PHONY : ftgl/utf8-utils.c.o

ftgl/utf8-utils.i: ftgl/utf8-utils.c.i

.PHONY : ftgl/utf8-utils.i

# target to preprocess a source file
ftgl/utf8-utils.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/utf8-utils.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/utf8-utils.c.i
.PHONY : ftgl/utf8-utils.c.i

ftgl/utf8-utils.s: ftgl/utf8-utils.c.s

.PHONY : ftgl/utf8-utils.s

# target to generate assembly for a file
ftgl/utf8-utils.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/utf8-utils.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/utf8-utils.c.s
.PHONY : ftgl/utf8-utils.c.s

ftgl/vector.o: ftgl/vector.c.o

.PHONY : ftgl/vector.o

# target to build an object file
ftgl/vector.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/vector.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/vector.c.o
.PHONY : ftgl/vector.c.o

ftgl/vector.i: ftgl/vector.c.i

.PHONY : ftgl/vector.i

# target to preprocess a source file
ftgl/vector.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/vector.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/vector.c.i
.PHONY : ftgl/vector.c.i

ftgl/vector.s: ftgl/vector.c.s

.PHONY : ftgl/vector.s

# target to generate assembly for a file
ftgl/vector.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/vector.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/vector.c.s
.PHONY : ftgl/vector.c.s

ftgl/vertex-attribute.o: ftgl/vertex-attribute.c.o

.PHONY : ftgl/vertex-attribute.o

# target to build an object file
ftgl/vertex-attribute.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/vertex-attribute.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/vertex-attribute.c.o
.PHONY : ftgl/vertex-attribute.c.o

ftgl/vertex-attribute.i: ftgl/vertex-attribute.c.i

.PHONY : ftgl/vertex-attribute.i

# target to preprocess a source file
ftgl/vertex-attribute.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/vertex-attribute.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/vertex-attribute.c.i
.PHONY : ftgl/vertex-attribute.c.i

ftgl/vertex-attribute.s: ftgl/vertex-attribute.c.s

.PHONY : ftgl/vertex-attribute.s

# target to generate assembly for a file
ftgl/vertex-attribute.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/vertex-attribute.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/vertex-attribute.c.s
.PHONY : ftgl/vertex-attribute.c.s

ftgl/vertex-buffer.o: ftgl/vertex-buffer.c.o

.PHONY : ftgl/vertex-buffer.o

# target to build an object file
ftgl/vertex-buffer.c.o:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/vertex-buffer.c.o
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/vertex-buffer.c.o
.PHONY : ftgl/vertex-buffer.c.o

ftgl/vertex-buffer.i: ftgl/vertex-buffer.c.i

.PHONY : ftgl/vertex-buffer.i

# target to preprocess a source file
ftgl/vertex-buffer.c.i:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/vertex-buffer.c.i
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/vertex-buffer.c.i
.PHONY : ftgl/vertex-buffer.c.i

ftgl/vertex-buffer.s: ftgl/vertex-buffer.c.s

.PHONY : ftgl/vertex-buffer.s

# target to generate assembly for a file
ftgl/vertex-buffer.c.s:
	$(MAKE) -f CMakeFiles/glez32.dir/build.make CMakeFiles/glez32.dir/ftgl/vertex-buffer.c.s
	$(MAKE) -f CMakeFiles/glez64.dir/build.make CMakeFiles/glez64.dir/ftgl/vertex-buffer.c.s
.PHONY : ftgl/vertex-buffer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... glez32"
	@echo "... glez64"
	@echo "... ftgl/distance-field.o"
	@echo "... ftgl/distance-field.i"
	@echo "... ftgl/distance-field.s"
	@echo "... ftgl/edtaa3func.o"
	@echo "... ftgl/edtaa3func.i"
	@echo "... ftgl/edtaa3func.s"
	@echo "... ftgl/font-manager.o"
	@echo "... ftgl/font-manager.i"
	@echo "... ftgl/font-manager.s"
	@echo "... ftgl/makefont.o"
	@echo "... ftgl/makefont.i"
	@echo "... ftgl/makefont.s"
	@echo "... ftgl/mat4.o"
	@echo "... ftgl/mat4.i"
	@echo "... ftgl/mat4.s"
	@echo "... ftgl/platform.o"
	@echo "... ftgl/platform.i"
	@echo "... ftgl/platform.s"
	@echo "... ftgl/text-buffer.o"
	@echo "... ftgl/text-buffer.i"
	@echo "... ftgl/text-buffer.s"
	@echo "... ftgl/texture-atlas.o"
	@echo "... ftgl/texture-atlas.i"
	@echo "... ftgl/texture-atlas.s"
	@echo "... ftgl/texture-font.o"
	@echo "... ftgl/texture-font.i"
	@echo "... ftgl/texture-font.s"
	@echo "... ftgl/utf8-utils.o"
	@echo "... ftgl/utf8-utils.i"
	@echo "... ftgl/utf8-utils.s"
	@echo "... ftgl/vector.o"
	@echo "... ftgl/vector.i"
	@echo "... ftgl/vector.s"
	@echo "... ftgl/vertex-attribute.o"
	@echo "... ftgl/vertex-attribute.i"
	@echo "... ftgl/vertex-attribute.s"
	@echo "... ftgl/vertex-buffer.o"
	@echo "... ftgl/vertex-buffer.i"
	@echo "... ftgl/vertex-buffer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

